{
  "throws": "invalid use of await inside of an async function (2:11)"
}